services:
  mysqldb:
    container_name: mysqldb
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: the_enchanted_message_bridge
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net

  the_enchanted_message_bridge:
    container_name: the_enchanted_message_bridge
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net


networks:
  springboot-mysql-net: